# Generated by Django 4.2.14 on 2025-05-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="star",
            field=models.IntegerField(default=0),
        ),
    ]
