# Generated by Django 4.2.14 on 2025-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0002_category_product_delete_vegetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
