# Generated by Django 4.2.14 on 2025-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0004_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
