# Generated by Django 4.2.14 on 2025-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keywords",
            field=models.TextField(
                blank=True, help_text="Comma-separated search terms"
            ),
        ),
    ]
