# Generated by Django 4.2.14 on 2025-04-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0005_alter_product_category_order_addtocart"),
    ]

    operations = [
        migrations.AddField(
            model_name="addtocart",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="addtocart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="fruitapp.product",
            ),
        ),
    ]
