# Generated by Django 4.2.14 on 2025-04-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0007_billingaddress_order_billing_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shippingfee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(default="380015", max_length=20)),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "local_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="billingaddress",
            name="local_fee",
        ),
        migrations.RemoveField(
            model_name="billingaddress",
            name="shipping_fee",
        ),
        migrations.RemoveField(
            model_name="billingaddress",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="billingaddress",
            name="Shippingfee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fruitapp.shippingfee",
            ),
        ),
    ]
