# Generated by Django 4.2.14 on 2025-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0008_shippingfee_remove_billingaddress_local_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingfee",
            name="zip_code",
            field=models.PositiveBigIntegerField(default="380015"),
        ),
    ]
