# Generated by Django 4.2.14 on 2025-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0010_remove_order_product_remove_order_quantity_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
