# Generated by Django 4.2.14 on 2025-05-25 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0010_order_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaddress",
            name="shippingfee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fruitapp.shippingfee",
            ),
        ),
    ]
