# Generated by Django 4.2.14 on 2025-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0011_billingaddress_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
