# Generated by Django 4.2.14 on 2025-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruitapp", "0012_billingaddress_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
