# Generated by Django 4.2.14 on 2025-04-24 11:53



from django.db import migrations
from django.contrib.auth.hashers import make_password

def migrate_users(apps, schema_editor):
    AuthUser = apps.get_model('auth', 'User')
    CustomUser = apps.get_model('fruitapp', 'User')
    
    # Create a default user for NULL references
    default_user, _ = CustomUser.objects.get_or_create(
        username='deleted_user',
        defaults={
            'email': 'deleted@example.com',
            'password': make_password(None),  # Unusable password
            'is_active': False,
            'is_staff': False,
            'is_superuser': False,
            'full_name': 'Deleted User'
        }
    )
    
    # Migrate all auth users
    for auth_user in AuthUser.objects.all():
        CustomUser.objects.update_or_create(
            id=auth_user.id,  # Preserve original IDs
            defaults={
                'username': auth_user.username,
                'email': auth_user.email,
                'password': auth_user.password,
                'is_active': auth_user.is_active,
                'is_staff': auth_user.is_staff,
                'is_superuser': auth_user.is_superuser,
                'full_name': f"{auth_user.first_name} {auth_user.last_name}".strip() or auth_user.username,
            }
        )
    
    # Update all foreign key references
    models_to_update = {
        'addtocart': 'user',
        'order': 'user',
        'billingaddress': 'user',
        # Add other models that reference User
    }
    
    for model_name, field_name in models_to_update.items():
        Model = apps.get_model('fruitapp', model_name)
        
        # First handle NULL values
        Model.objects.filter(**{f"{field_name}__isnull": True}).update(
            **{field_name: default_user}
        )
        
        # Then update remaining references (IDs already match)

class Migration(migrations.Migration):
    dependencies = [
        ('fruitapp', '0017_alter_addtocart_user_alter_billingaddress_user_and_more'),  # Replace with actual previous migration
    ]

    operations = [
        migrations.RunPython(migrate_users),
    ]