# Generated by Django 4.2.14 on 2025-04-24 12:42

from django.db import migrations
from django.conf import settings
from django.db import models

class Migration(migrations.Migration):
    dependencies = [
        ('fruitapp', '0018_migrate_auth_user_to_custom'),  # Your data migration
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,  # Reference through settings
                on_delete=models.CASCADE,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
            ),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=models.CASCADE,
            ),
        ),
    ]